version: '2.4'

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: ${RESTART_POLICY}
    network_mode: host
    labels:
      org.label-schema.group: "monitored"
    environment:
      - PUID
      - PGID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/urbackup:/var/urbackup
      - $BACKUPS:/backups
    cap_add:
      - SYS_ADMIN
    cpu_shares: 1024
    cpus: 3
    mem_limit: 2gb
    memswap_limit: 2gb

# vim: et ci pi sts=2 sw=2 ts=2
