version: '2.4'

services:
  rtorrent-ps-ch:
    hostname: rtorrent
    build: ./rtorrent-ps-ch
    container_name: rtorrent
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_RTORRENT}
    # command: tail -f /dev/null
    volumes:
      - ./rtorrent-ps-ch:/app
      - /opt/rtorrent:/config
      - ${DOWNLOADS}:${DOWNLOADS}
    environment:
      - RTORRENT_USER=${RTORRENT_USER}
    ports:
      - '${RTORRENT_PORT}:${RTORRENT_PORT}'
      - '${RTORRENT_PORT}:${RTORRENT_PORT}/udp'
    cpu_shares: 64
    cpus: 2
    mem_limit: 1gb
    memswap_limit: 1gb


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_P2P}
    driver_opts:
      com.docker.network.bridge.name: br-p2p

# vim: et ci pi sts=2 sw=2 ts=2
