version: '2.4'

services:
  rtorrent-ps-ch:
    hostname: rtorrent
    build: ./rtorrent-ps-ch
    container_name: rtorrent
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: ${RESTART_POLICY}
    network_mode: host
    # command: tail -f /dev/null
    volumes:
      - ./rtorrent-ps-ch:/app
      - /opt/rtorrent:/config
      - ${DOWNLOADS}:${DOWNLOADS}
    environment:
      - RTORRENT_USER=${RTORRENT_USER}
    cpu_shares: 64
    cpus: 2
    mem_limit: 512mb
    memswap_limit: 512mb


# vim: et ci pi sts=2 sw=2 ts=2
