version: '2.4'
services:

  gitlab-ce:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:latest
    hostname: ${GITLAB_DOMAIN}
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_GITLAB}
    ports:
      - '127.0.0.1:8085:80'
      - '55055:22'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
      - /opt/gitlab/uploads:/var/opt/gitlab/gitlab-rails/uploads
      - /opt/gitlab-lfs:/var/opt/gitlab-lfs
      - /opt/gitlab-repos:/var/opt/gitlab-repos
    cpus: 3
    mem_limit: 6gb
    memswap_limit: 6gb

  #gitlab-runner:
  #  container_name: gitlab-runner
  #  image: gitlab/gitlab-runner:alpine
  #  mac_address: ${MAC_GITLAB_RUNNER}
  #  depends_on:
  #    - gitlab-ce
  #  extra_hosts:
  #    - "${GITLAB_DOMAIN}:${LAN_IP}"
  #  volumes:
  #    - /opt/gitlab/gitlab-runner:/etc/gitlab-runner
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  cpus: 3
  #  mem_limit: 6gb
  #  memswap_limit: 6gb

  code-server:
    container_name: code-server
    # image: ghcr.io/linuxserver/code-server
    build: ./code-server
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_CODESERVER}
    ports:
      - '127.0.0.1:8095:8443'
    environment:
      - PUID=${CODESERVER_UID}
      - PGID=${CODESERVER_GID}
      - PROXY_DOMAIN=${CODESERVER_DOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/code-server:/config
      - /opt/docker:/var/lib/docker
      - /var/run/docker:/var/run/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CODESERVER_HOME_DATA}:/src
      - ${CODESERVER_SHARED_DATA}:${CODESERVER_SHARED_DATA}
    cpus: 3
    mem_limit: 6gb
    memswap_limit: 6gb


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_GITLAB}
    driver_opts:
      com.docker.network.bridge.name: br-gitlab

# vim: et ci pi sts=2 sw=2 ts=2
