version: '2.4'

services:
  unifi:
    image: linuxserver/unifi-controller:latest
    container_name: unifi
    restart: on-failure
    mac_address: ${MAC_UNIFI}
    ports:
      - '${LAN_IP}:3478:3478/udp'
      - '${LAN_IP}:6789:6789'
      - '${LAN_IP}:8080:8080'
      - '${LAN_IP}:8081:8081'
      - '${LAN_IP}:8443:8443'
      - '${LAN_IP}:8880:8880'
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/acme:/etc/acme
      - /opt/unifi:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    cpus: 1
    mem_limit: 1gb
    memswap_limit: 1gb
    healthcheck:
      test: curl --fail -k -s https://127.0.0.1:8443/
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_UNIFI}
    driver_opts:
      com.docker.network.bridge.name: br-unifi

# vim: et ci pi sts=2 sw=2 ts=2
