version: '2.4'

services:
  #comskip:
  #  build: ./comskip
  #  container_name: comskip
  #  restart: ${RESTART_POLICY}
  #  mac_address: ${MAC_COMSKIP}
  #  devices:
  #    - /dev/dri:/dev/dri
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #    - LOG_COMSKIP=${LOG_COMSKIP}
  #    - RECORDINGS=${U7D_DIR}
  #  volumes:
  #    - /etc/localtime:/etc/localtime
  #    - ./comskip:/app
  #    - ${U7D_DIR}:${U7D_DIR}
  #  cpu_shares: 64
  #  cpus: 3
  #  mem_limit: 2gb
  #  memswap_limit: 2gb

  emby:
    # image: ghcr.io/linuxserver/emby
    image: ghcr.io/linuxserver/emby:version-4.5.4.0
    # build: ./emby
    container_name: emby
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_EMBY}
    ports:
      - '${LAN_IP}:8096:8096'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/emby:/config
      - /storage/documentaries:/storage/documentaries
      - /storage/movies:/storage/movies
      - /storage/peliculas:/storage/peliculas
      - /storage/recordings:/storage/recordings
      - /storage/series:/storage/series
      - /storage/timeshift:/storage/timeshift
      - /storage/tvshows:/storage/tvshows
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    cpu_shares: 1024
    cpus: 3
    mem_limit: 2gb
    memswap_limit: 2gb
    healthcheck:
      test: curl --fail -s http://127.0.0.1:8096/
      interval: 30s
      timeout: 5s
      retries: 3

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_MEDUSA}
    ports:
      - '127.0.0.1:8083:8081'
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/medusa:/config
      - /storage/downloads:/storage/downloads
      - /storage/tvshows:/storage/tvshows
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    cpu_shares: 512
    cpus: 1
    mem_limit: 512mb
    memswap_limit: 512mb
    healthcheck:
      test: curl --fail -s http://127.0.0.1:8081/
      interval: 30s
      timeout: 5s
      retries: 3

  movistar_u7d:
    build: ./movistar_u7d
    container_name: movistar_u7d
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: ${RESTART_POLICY}
    networks:
      tvlan:
        ipv4_address: ${U7D_ADDRESS}
      iptv:
        ipv4_address: ${IPTV_ADDRESS}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./movistar_u7d:/app
      - ${U7D_HOME}:/home
      - ${RECORDINGS}:${RECORDINGS}
    environment:
      - U7D_UID=${U7D_UID}
      - U7D_GID=${U7D_GID}
      - LAN_IP=${LAN_IP}
      - RECORDINGS=${RECORDINGS}
      - MAC_IPTV_U7D=${MAC_IPTV_U7D}
      - MAC_MOVISTAR_U7D=${MAC_MOVISTAR_U7D}
      - IPTV_GW=${IPTV_GW}
      - U7D_GW=${U7D_GW}
    devices:
      - /dev/dri:/dev/dri
    cpu_shares: 4096
    cpus: 4
    mem_limit: 1gb
    memswap_limit: 1gb
    healthcheck:
      test: /app/health.sh
      interval: 300s
      timeout: 5s
      retries: 3

  flood:
    hostname: flood
    image: jesec/flood
    container_name: flood
    user: ${PUID}:${PGID}
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_FLOOD}
    command: --port 9091 --allowedpath ${DOWNLOADS}
    environment:
      HOME: /config
    volumes:
      - /opt/rtorrent:/config
      - ${DOWNLOADS}:${DOWNLOADS}
    ports:
      - '127.0.0.1:9091:9091'
    cpus: 2
    cpuset: 5,1
    mem_limit: 128mb
    memswap_limit: 128mb
    healthcheck:
      test: nc -zv 127.0.0.1 9091
      interval: 30s
      timeout: 5s
      retries: 3

  rtorrent:
    hostname: rtorrent
    build: ./rtorrent
    container_name: rtorrent
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_RTORRENT}
    # command: -n -o import=/config/my-rtorrent.rc
    volumes:
      - ./rtorrent:/app
      - /opt/rtorrent:/config
      - ${DOWNLOADS}:${DOWNLOADS}
    environment:
      - RTORRENT_USER=${RTORRENT_USER}
    ports:
      - '${RTORRENT_PORT}:${RTORRENT_PORT}'
      - '${RTORRENT_PORT}:${RTORRENT_PORT}/udp'
    cpu_shares: 64
    cpus: 2
    cpuset: 1,5
    mem_limit: 512mb
    memswap_limit: 512mb

  #transmission:
  #  build: ./transmission
  #  container_name: transmission
  #  cap_add:
  #    - SYS_NICE
  #  restart: ${RESTART_POLICY}
  #  mac_address: ${MAC_TRANSMISSION}
  #  ports:
  #    - '${TRANSMISSION_PORT}:${TRANSMISSION_PORT}'
  #    - '${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp'
  #    - '127.0.0.1:9091:9091'
  #  volumes:
  #    - /etc/localtime:/etc/localtime
  #    - /opt/transmission:/config
  #    - /storage/downloads:/storage/downloads
  #    - /storage/downloads/watch:/watch
  #  environment:
  #    #- TRANSMISSION_WEB_HOME=/combustion-release/
  #    - TRANSMISSION_WEB_HOME=/kettu/
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #  cpu_shares: 128
  #  cpus: 1
  #  cpuset: 1,5
  #  mem_limit: 2gb
  #  memswap_limit: 2gb
  #  healthcheck:
  #    test: curl --fail -s http://127.0.0.1:9091/
  #    interval: 30s
  #    timeout: 60s
  #    retries: 3

  #tvheadend:
  #  build: ./tvheadend
  #  container_name: tvheadend
  #  cap_add:
  #    - NET_BROADCAST
  #    - SYS_ADMIN
  #    - SYS_NICE
  #  restart: ${RESTART_POLICY}
  #  networks:
  #    tvlan:
  #  mac_address: ${MAC_TVHEADEND}
  #  ports:
  #    - '${LAN_IP}:9981:9981'
  #    - '${LAN_IP}:9982:9982'
  #  volumes:
  #    - /etc/localtime:/etc/localtime
  #    - /opt/tvheadend:/config
  #    - /storage/recordings:/recordings
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #  #  - RUN_OPTS=<run options here> #optional
  #  devices:
  #    - /dev/dri:/dev/dri
  #  cpu_shares: 2048
  #  cpus: 2
  #  mem_limit: 1gb
  #  memswap_limit: 1gb
  #  healthcheck:
  #    test: wget http://127.0.0.1:9981/ 2>&1 | grep -q ':9981... connected.'
  #    interval: 30s
  #    timeout: 5s
  #    retries: 3


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_MULTIMEDIA}
    driver_opts:
      com.docker.network.bridge.name: br-multimedia
  iptv:
    driver: macvlan
    driver_opts:
      parent: eth0.2
    ipam:
      config:
         - subnet: ${IPTV_NET}
  tvlan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_TVLAN}
    driver_opts:
      com.docker.network.bridge.name: br-tvlan

# vim: et ci pi sts=2 sw=2 ts=2
