version: '2.4'

services:
  #comskip:
  #  build: ./comskip
  #  container_name: comskip
  #  restart: ${RESTART_POLICY}
  #  mac_address: ${MAC_COMSKIP}
  #   labels:
  #     org.label-schema.group: "monitored"
  #  devices:
  #    - /dev/dri:/dev/dri
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #    - LOG_COMSKIP=${LOG_COMSKIP}
  #    - RECORDINGS=${U7D_DIR}
  #  volumes:
  #    - /etc/localtime:/etc/localtime
  #    - ./comskip:/app
  #    - ${U7D_DIR}:${U7D_DIR}
  #  cpu_shares: 64
  #  cpus: 3
  #  mem_limit: 2gb
  #  memswap_limit: 2gb

  flood:
    hostname: flood
    image: jesec/flood
    container_name: flood
    user: ${PUID}:${PGID}
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_FLOOD}
    labels:
      org.label-schema.group: "monitored"
    command: --allowedpath ${DOWNLOADS}
    environment:
      HOME: /config
    volumes:
      - /opt/rtorrent:/config
      - ${DOWNLOADS}:${DOWNLOADS}
    ports:
      - '127.0.0.1:9091:3000'
    cpus: 2
    mem_limit: 512mb
    memswap_limit: 512mb
    healthcheck:
      test: nc -zv 127.0.0.1 9091
      interval: 30s
      timeout: 5s
      retries: 3

  jellyfin:
    build: ./jellyfin
    container_name: jellyfin
    restart: ${RESTART_POLICY}
    privileged: true
    network_mode: host
    labels:
      org.label-schema.group: "monitored"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/jellyfin:/config
      - /opt/jellyfin-cache:/cache
      - /storage/documentaries:/storage/documentaries
      - /storage/movies:/storage/movies
      - /storage/peliculas:/storage/peliculas
      - /storage/recordings:/storage/recordings
      - /storage/series:/storage/series
      - /storage/timeshift:/storage/timeshift
      - /storage/tvshows:/storage/tvshows
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    cpu_shares: 1024
    cpus: 3
    mem_limit: 2gb
    memswap_limit: 2gb
    #healthcheck:
    #  test: curl --fail -s http://127.0.0.1:8096/
    #  interval: 30s
    #  timeout: 5s
    #  retries: 3

  medusa:
    image: linuxserver/medusa
    container_name: medusa
    restart: ${RESTART_POLICY}
    mac_address: ${MAC_MEDUSA}
    labels:
      org.label-schema.group: "monitored"
    ports:
      - '127.0.0.1:8083:8081'
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/medusa:/config
      - /storage/downloads:/storage/downloads
      - /storage/tvshows:/storage/tvshows
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    cpu_shares: 512
    cpus: 1
    mem_limit: 512mb
    memswap_limit: 512mb
    healthcheck:
      test: curl --fail -s http://127.0.0.1:8081/
      interval: 30s
      timeout: 5s
      retries: 3

  movistar_u7d:
    # build: ./movistar_u7d
    image: registry.marcet.info/javier/movistar-u7d
    container_name: movistar_u7d
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: ${RESTART_POLICY}
    network_mode: host
    labels:
      org.label-schema.group: "monitored"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./movistar_u7d:/app
      - ${RECORDINGS}:${RECORDINGS}
      - ${U7D_HOME}:/home
    environment:
      # - DEBUG=1
      - IPTV_BW=${IPTV_BW}
      - IPTV_IFACE=${IPTV_IFACE}
      - LAN_IP=${LAN_IP}
      # - MP4_OUTPUT=${MP4_OUTPUT}
      - RECORDINGS=${RECORDINGS}
      - U7D_UID=${U7D_UID}
      # - VERBOSE_LOGS=${VERBOSE_LOGS}
    devices:
      - /dev/dri:/dev/dri
    cpu_shares: 8192
    cpus: 4
    mem_limit: 3gb
    memswap_limit: 3gb
    healthcheck:
      test: /app/health.sh
      interval: 300s
      timeout: 5s
      retries: 3


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_MULTIMEDIA}
    driver_opts:
      com.docker.network.bridge.name: br-multimedia

# vim: et ci pi sts=2 sw=2 ts=2
